### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by DeadSix27** [shinchiro/mpv-winbuild-cmake#25]
- [ ] Auto-detect packages/programs required (e.g gcc,nasm,...)
- [ ] Update to Qt 5.9 (requires updated patches, don't think any of the sources I got them from have updated yet, e.g Arch packagers)
- [ ] Make it easier to seperate the package json data (e.g remote hosting)

**Comment by DeadSix27** [comment]
F... sorry shin ;) midnight derp by me, wrong issue tracker heh
